//constantes para storear cosas:
const ADD_PRODUCTS ="ADD_PRODUCTS"
const ADD_PRODUCT="ADD_PRODUCT"
const ADD_CART ="ADD_CART"
const SET_CART ="SET_CART"


export {ADD_PRODUCTS, SET_CART, ADD_CART,ADD_PRODUCT}