//constantes para storear cosas:
const ADD_PRODUCTS ="ADD_PRODUCTS"
const ADD_PRODUCT="ADD_PRODUCT"
const ADD_CART ="ADD_CART"
const SET_CART ="SET_CART"
const REM_CART ="REM_CART"
const LOG_USER = "LOG_USER"
const DELOG_USER = "DELOG_USER"
const ADD_CATS = "ADD_CATS"

export {ADD_PRODUCTS, SET_CART, ADD_CART,ADD_PRODUCT, REM_CART, LOG_USER, DELOG_USER, ADD_CATS}